name: PR Ephemeral Environment

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]

permissions:
  contents: write
  pull-requests: write

jobs:
  ephemeral:
    uses: fullstack-pw/pipelines/.github/workflows/ephemeral-environment.yml@main
    with:
      image-name: library/cks-frontend
      dev-hostname-placeholder: dev.cks.fullstack.pw
      deployment-name: cks-frontend
      cypress-spec: cypress/e2e/cks-frontend.cy.js
      cypress-env-key: CKS_FRONTEND_URL
    secrets: inherit # pragma: allowlist secret
